title: "zenn-qiita-mute-warning"
description: "zenn-qiita-mute-warning"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/zenn-qiita-mute-warning
plugins:
  - jekyll-sitemap
